---
name: Authentication Failure Simulation - AUTH401
on:
  workflow_dispatch:

jobs:
  authentication-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Authentication Failure
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Attempting login for user: admin" | tee -a test.log
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Invalid username and password" | tee -a test.log
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default credentials" | tee -a test.log
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0" | tee -a test.log
