---
name: Build Script Error Simulation - BLD001
on:
  workflow_dispatch:

jobs:
  build-script-error:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build Script Error
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Executing build.gradle script..." | tee -a test.log
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Syntax error in build.gradle at line 23" | tee -a test.log
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default build configuration" | tee -a test.log
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0" | tee -a test.log
