---
name: Null Reference Simulation - NULL500
on:
  workflow_dispatch:

jobs:
  null-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Null Reference
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Executing operation..." | tee -a test.log
          sleep 2
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] NullPointer Exception at 'line'" | tee -a test.log
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Initialized default object" | tee -a test.log
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0" | tee -a test.log
