name: Apply Fix
on:
  workflow_dispatch:
  
jobs:
  apply-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Extract Fix
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Getting json of the fix and converting into actionable script..."" | tee -a test.log
          $fix_commands = $(echo '${{ github.event.client_payload.fix_steps }}' | jq -r '.[]?')
          if [ -z "$fix_commands" ]; then
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] No fix steps provided." | tee -a test.log
            exit 1
          else
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fix steps received: $fix_commands" | tee -a test.log
            echo "$fix_commands" | sed 's/^/echo Running: & \n&/' > fix.sh
            chmod +x fix.sh
          fi
          
      - name: Execute Fix
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Executing fix script..." | tee -a test.log
          ./fix.sh || { echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Fix script execution failed." | tee -a test.log; exit 1; }
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fix script executed successfully." | tee -a test.log
